=== 3imed-jaberi/play-with-xml-and-dtd/Ex 03/03.dtd
<!ELEMENT service (client+, commande*, article+, representant+, region+,  detail*, prospection+)>
<!ELEMENT client EMPTY>
<!ELEMENT article EMPTY>
<!ELEMENT commande EMPTY>
<!ELEMENT representant EMPTY>
<!ELEMENT region EMPTY>
<!ELEMENT detail EMPTY>
<!ELEMENT prospection EMPTY>
<!ATTLIST client 
  numCli CDATA #REQUIRED
  nomCli CDATA #REQUIRED
  adCli CDATA #IMPLIED
>
<!ATTLIST 
  article numA CDATA #REQUIRED
  libA CDATA #IMPLIED
  puA CDATA #IMPLIED
  stockA CDATA #IMPLIED
>
<!ATTLIST commande 
  numC CDATA #REQUIRED
  dateC CDATA #REQUIRED
  numCli CDATA #REQUIRED
  numRep CDATA #REQUIRED
>
<!ATTLIST representant 
  numRep CDATA #REQUIRED
  nomRep CDATA #REQUIRED
  salRep CDATA #IMPLIED
  tauxRep CDATA #IMPLIED
>
<!ATTLIST region 
  nomR CDATA #REQUIRED
  popR CDATA #IMPLIED
>
<!ATTLIST detail 
  numC CDATA #REQUIRED
  numA CDATA #REQUIRED
  qte CDATA #REQUIRED
>
<!ATTLIST prospection 
  numRep CDATA #REQUIRED
  nomR CDATA #REQUIRED
>

=== 3imed-jaberi/play-with-xml-and-dtd/Ex 03/03.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE service SYSTEM "03.dtd">

<service>
  <client 
    numCli="123" 
    nomCli="DUBOIS" 
    adCli="Dijon" 
  />
  <client 
    numCli="124" 
    nomCli="DUGENOU" 
    adCli="OrlÃ©ans" 
  />
  <client 
    numCli="125" 
    nomCli="DURACUIRE" 
    adCli="Bordeaux" 
  />
  <client 
    numCli="126" 
    nomCli="DUPONT" 
    adCli="Rennes" 
  />
  <commande 
    numC="1024" 
    dateC="03/01/2008" 
    numCli="123" 
    numRep="10" 
  />
  <commande 
    numC="1025" 
    dateC="12/01/2008" 
    numCli="123" 
    numRep="11" 
  />
  <commande 
    numC="1026" 
    dateC="16/01/2008" 
    numCli="124" 
    numRep="12" 
  />
  <commande 
    numC="1027" 
    dateC="02/02/2008" 
    numCli="125" 
    numRep="12" 
  />
  <article 
    numA="10123" 
    libA="couteau F31" 
    puA="12" 
    stockA="60" 
  />
  <article 
    numA="12345" 
    libA="fourchette A45" 
    puA="14" 
    stockA="32" 
  />
  <article 
    numA="34567" 
    libA="verre P98" 
    puA="13" 
    stockA="24" 
  />
  <article 
    numA="65654" 
    libA="assiette R21" 
    puA="18" 
    stockA="20" 
  />
  <representant 
    numRep="10"
    nomRep="DUPUIS" 
    salRep="1200" 
    tauxRep="5" 
  />
  <representant 
    numRep="11"
    nomRep="DUBALAI" 
    salRep="1300" 
    tauxRep="6" 
  />
  <representant 
    numRep="12" 
    nomRep="DUCHEMIN" 
    salRep="1250" 
    tauxRep="4" 
  />
  <representant 
    numRep="13" 
    nomRep="DUMESNIL" 
    salRep="1400" 
    tauxRep="5" 
  />
  <region 
    nomR="Bourgogne" 
    popR="1,623" 
  />
  <region 
    nomR="Bretagne" 
    popR="3,080" 
  />
  <region 
    nomR="Centre" 
    popR="2,505" 
  />
  <region 
    nomR="Aquitaine" 
    popR="3,098" 
  />
  <detail 
    numC="1024" 
    numA="10123" 
    qte="20" 
  />
  <detail 
    numC="1024" 
    numA="12345" 
    qte="50" 
  />
  <detail 
    numC="1025" 
    numA="10123" 
    qte="30" 
  />
  <detail 
    numC="1026" 
    numA="34567" 
    qte="25" 
  />
  <detail 
    numC="1026" 
    numA="65654" 
    qte="20" 
  />
  <detail 
    numC="1027" 
    numA="12345" 
    qte="15" 
  />
  <prospection 
    numRep="10" 
    nomR="Bourgogne" 
  />
  <prospection 
    numRep="10" 
    nomR="Centre" 
  />
  <prospection 
    numRep="11" 
    nomR="Bourgogne" 
  />
  <prospection 
    numRep="11" 
    nomR="Aquitaine" 
  />
  <prospection 
    numRep="12" 
    nomR="Centre" 
  />
  <prospection 
    numRep="13" 
    nomR="Bretagne" 
  />
  <prospection 
    numRep="12" 
    nomR="Aquitaine" 
  />
</service>
